<a href="https://colab.research.google.com/github/2303A52432/GA_AI_2303A52432/blob/main/GAI_ASS_1_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A.YASHWANTH

BATCH>>42

2303A52432

ASSIGNMENT-1

In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Actual values and predicted values from the table
YActual = np.array([20, 30, 40, 50, 60])
YPred = np.array([20.530, 30.340, 40.250, 50.660, 60.7])

# 1. Mean Absolute Error (MAE)
MAE_scratch = np.mean(np.abs(YActual - YPred))

# 2. Mean Squared Error (MSE)
MSE_scratch = np.mean((YActual - YPred) ** 2)

# 3. Root Mean Squared Error (RMSE)
RMSE_scratch = np.sqrt(MSE_scratch)

# 4. R-squared (R²)
SS_total = np.sum((YActual - np.mean(YActual)) ** 2)
SS_residual = np.sum((YActual - YPred) ** 2)
R2_scratch = 1 - (SS_residual / SS_total)

# Print the error metrics calculated from scratch
print("Error metrics from scratch:")
print(f"Mean Absolute Error (MAE): {MAE_scratch}")
print(f"Mean Squared Error (MSE): {MSE_scratch}")
print(f"Root Mean Squared Error (RMSE): {RMSE_scratch}")
print(f"R-squared (R²): {R2_scratch}")

# 5. Compare with sklearn library functions
MAE_sklearn = mean_absolute_error(YActual, YPred)
MSE_sklearn = mean_squared_error(YActual, YPred)
RMSE_sklearn = np.sqrt(MSE_sklearn)
R2_sklearn = r2_score(YActual, YPred)

# Print the error metrics from sklearn
print("\nError metrics from sklearn:")
print(f"Mean Absolute Error (MAE): {MAE_sklearn}")
print(f"Mean Squared Error (MSE): {MSE_sklearn}")
print(f"Root Mean Squared Error (RMSE): {RMSE_sklearn}")
print(f"R-squared (R²): {R2_sklearn}")


Error metrics from scratch:
Mean Absolute Error (MAE): 0.4960000000000001
Mean Squared Error (MSE): 0.2769200000000001
Root Mean Squared Error (RMSE): 0.5262318880493656
R-squared (R²): 0.9986154

Error metrics from sklearn:
Mean Absolute Error (MAE): 0.4960000000000001
Mean Squared Error (MSE): 0.2769200000000001
Root Mean Squared Error (RMSE): 0.5262318880493656
R-squared (R²): 0.9986154


In [15]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Actual values and predicted values from the table
YActual = np.array([0, 1, 2, 0, 1, 0, 0, 1, 1, 2])
YPred = np.array([0, 1, 0, 0, 0, 0, 1, 2, 2, 2])

# 1. Accuracy
accuracy_scratch = np.mean(YActual == YPred)

# 2. Precision (for each class)
# We calculate Precision for each class separately (0, 1, and 2)
def precision(y_true, y_pred, class_label):
 TP = np.sum((y_true == class_label) & (y_pred == class_label))  # True positives
 FP = np.sum((y_true != class_label) & (y_pred == class_label))  # False positives
 return TP / (TP + FP) if (TP + FP) > 0 else 0

precision_scratch = [precision(YActual, YPred, i) for i in np.unique(YActual)]

# 3. Recall (for each class)
def recall(y_true, y_pred, class_label):
 TP = np.sum((y_true == class_label) & (y_pred == class_label))  # True positives
 FN = np.sum((y_true == class_label) & (y_pred != class_label))  # False negatives
 return TP / (TP + FN) if (TP + FN) > 0 else 0

recall_scratch = [recall(YActual, YPred, i) for i in np.unique(YActual)]

# 4. F1-Score (for each class)
def f1_score_class(precision, recall):
 return 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

f1_scratch = [f1_score_class(p, r) for p, r in zip(precision_scratch, recall_scratch)]

# Print the metrics calculated from scratch
print("Evaluation metrics from scratch:")
print(f"Accuracy: {accuracy_scratch}")
print(f"Precision for each class (0, 1, 2): {precision_scratch}")
print(f"Recall for each class (0, 1, 2): {recall_scratch}")
print(f"F1-Score for each class (0, 1, 2): {f1_scratch}")

# 5. Compare with sklearn library functions
accuracy_sklearn = accuracy_score(YActual, YPred)
precision_sklearn = precision_score(YActual, YPred, average=None, labels=np.unique(YActual))
recall_sklearn = recall_score(YActual, YPred, average=None, labels=np.unique(YActual))
f1_sklearn = f1_score(YActual, YPred, average=None, labels=np.unique(YActual))

# Print the metrics from sklearn
print("\nEvaluation metrics from sklearn:")
print(f"Accuracy: {accuracy_sklearn}")
print(f"Precision for each class (0, 1, 2): {precision_sklearn}")
print(f"Recall for each class (0, 1, 2): {recall_sklearn}")
print(f"F1-Score for each class (0, 1, 2): {f1_sklearn}")

# 6. Confusion Matrix (optional but useful for classification problems)
conf_matrix = confusion_matrix(YActual, YPred)
print("\nConfusion Matrix:")
print(conf_matrix)


Evaluation metrics from scratch:
Accuracy: 0.5
Precision for each class (0, 1, 2): [0.6, 0.5, 0.3333333333333333]
Recall for each class (0, 1, 2): [0.75, 0.25, 0.5]
F1-Score for each class (0, 1, 2): [0.6666666666666665, 0.3333333333333333, 0.4]

Evaluation metrics from sklearn:
Accuracy: 0.5
Precision for each class (0, 1, 2): [0.6        0.5        0.33333333]
Recall for each class (0, 1, 2): [0.75 0.25 0.5 ]
F1-Score for each class (0, 1, 2): [0.66666667 0.33333333 0.4       ]

Confusion Matrix:
[[3 1 0]
 [1 1 2]
 [1 0 1]]
